apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detector-deployment
spec:
  selector:
    matchLabels:
      app: facedetect
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: facedetect
    spec:
      containers:
      - name: facedetect
        image: jkumariucb/facedetect:v1
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-cam
        securityContext:
          privileged: true
      volumes:
      - name: dev-cam
        hostPath:
          path: /dev/video0
